# Generated by Django 3.2.23 on 2023-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('length', models.PositiveIntegerField()),
                ('widht', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
                ('cathegory', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
