# Generated by Django 3.2.23 on 2023-12-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='cathegory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='widht',
            new_name='width',
        ),
    ]
