# Generated by Django 3.2.23 on 2023-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0002_auto_20231212_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='length',
            field=models.PositiveIntegerField(db_column='length'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(db_column='widht'),
        ),
    ]
