# Generated by Django 3.2.23 on 2023-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0003_auto_20231212_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
