# Generated by Django 3.2.23 on 2023-12-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0004_alter_artwork_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='depth',
        ),
    ]
