# Generated by Django 3.2.23 on 2023-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
