# Generated by Django 3.2.23 on 2023-12-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0008_newprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newprofile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
