# Generated by Django 3.2.23 on 2023-12-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0010_category_customer_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artspot.medium'),
        ),
    ]
