# Generated by Django 3.2.23 on 2023-12-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspot', '0011_auto_20231218_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(db_column='length', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(db_column='width', default=0),
            preserve_default=False,
        ),
    ]
